server:
  port: 8090
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  data:
    mongodb:
      authentication-database: testdb
      host: localhost:27017
      database: testdb
      username: admin
      password: admindocker
debug: true